# Generated by Django 4.0 on 2022-03-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Suppliers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suppliercompany',
            old_name='businessIdentity',
            new_name='businessIdentityNo',
        ),
        migrations.AddField(
            model_name='suppliersaccount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='suppliersaccount',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='suppliersaccount',
            name='start_date',
            field=models.DateField(auto_now=True),
        ),
    ]
