# Generated by Django 4.0 on 2022-03-25 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Suppliers', '0003_suppliersaccount_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('barcode', models.BigIntegerField()),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Suppliers.productcategory')),
            ],
        ),
        migrations.CreateModel(
            name='WareHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('supplierCompany', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Suppliers.suppliercompany')),
            ],
        ),
        migrations.CreateModel(
            name='StockDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockNo', models.BigIntegerField()),
                ('price', models.BigIntegerField()),
                ('products', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Suppliers.products')),
                ('warehouseId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Suppliers.warehouse')),
            ],
        ),
    ]
