# Generated by Django 4.0 on 2022-03-26 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Suppliers', '0004_productcategory_products_warehouse_stockdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockdetails',
            old_name='price',
            new_name='pricePerUnit',
        ),
        migrations.RenameField(
            model_name='stockdetails',
            old_name='products',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='stockdetails',
            old_name='stockNo',
            new_name='stockQuantity',
        ),
        migrations.RenameField(
            model_name='stockdetails',
            old_name='warehouseId',
            new_name='wareHouse',
        ),
    ]
