# Generated by Django 4.0 on 2022-04-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Suppliers', '0005_rename_price_stockdetails_priceperunit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='UOMConversion',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='altunitOfMeasure',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Products/image/'),
        ),
        migrations.AddField(
            model_name='products',
            name='unitOfMeasure',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='stockdetails',
            name='out_of_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stockdetails',
            name='unitOfMeasure',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
